### ISSUE TITLE
Fix Merge Conflict in src/config/config.js

### ISSUE THREAD

**Issue by nafisfaysal** [CopywriterPro-ai/copywriterproai-backend#2]
Description:

A merge conflict needs to be resolved in src/config/config.js. Please review and fix the conflict to ensure the file is correctly merged.

File Path: [src/config/config.js](https://github.com/CopywriterPro-ai/copywriterproai-backend/blob/main/src/config/config.js?fbclid=IwZXh0bgNhZW0CMTAAAR0xW05TFpLk7KmJP0ZgoIDgUzKCp9MB98r2jfqzzlkTiAVD-qbBAjSEuMw_aem_ZmFrZWR1bW15MTZieXRlcw)

Steps:

Review conflicting changes.
Resolve the conflict.
Test to ensure no issues.

**Comment by andemosa** [comment]
Good day @nafisfaysal .

I had a look at this issue and I noticed that the merge conflict is because of editing the environment variables for Passport.

To fix the merge conflict, we need to be sure if the environment variables should be kept or they should be removed.

**Comment by nafisfaysal** [comment]
@andemosa Great. You should keep the environment variables for Passport. Thank you so much for taking care of it.

**Comment by andemosa** [comment]
I have created a PR for this. #3
